// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetworkMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_NetworkMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_NetworkMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_NetworkMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_NetworkMessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_NetworkMessage_2eproto;
class HeartbeatMessage;
class HeartbeatMessageDefaultTypeInternal;
extern HeartbeatMessageDefaultTypeInternal _HeartbeatMessage_default_instance_;
class NetworkMessage;
class NetworkMessageDefaultTypeInternal;
extern NetworkMessageDefaultTypeInternal _NetworkMessage_default_instance_;
class PlayerAttributeMessage;
class PlayerAttributeMessageDefaultTypeInternal;
extern PlayerAttributeMessageDefaultTypeInternal _PlayerAttributeMessage_default_instance_;
class PlayerAttributeMessage_AmmoEntry_DoNotUse;
class PlayerAttributeMessage_AmmoEntry_DoNotUseDefaultTypeInternal;
extern PlayerAttributeMessage_AmmoEntry_DoNotUseDefaultTypeInternal _PlayerAttributeMessage_AmmoEntry_DoNotUse_default_instance_;
class PlayerAttributeMessage_WeaponsEntry_DoNotUse;
class PlayerAttributeMessage_WeaponsEntry_DoNotUseDefaultTypeInternal;
extern PlayerAttributeMessage_WeaponsEntry_DoNotUseDefaultTypeInternal _PlayerAttributeMessage_WeaponsEntry_DoNotUse_default_instance_;
class PlayerStateMessage;
class PlayerStateMessageDefaultTypeInternal;
extern PlayerStateMessageDefaultTypeInternal _PlayerStateMessage_default_instance_;
class PlayerUpdateMessage;
class PlayerUpdateMessageDefaultTypeInternal;
extern PlayerUpdateMessageDefaultTypeInternal _PlayerUpdateMessage_default_instance_;
class Vector3;
class Vector3DefaultTypeInternal;
extern Vector3DefaultTypeInternal _Vector3_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::HeartbeatMessage* Arena::CreateMaybeMessage<::HeartbeatMessage>(Arena*);
template<> ::NetworkMessage* Arena::CreateMaybeMessage<::NetworkMessage>(Arena*);
template<> ::PlayerAttributeMessage* Arena::CreateMaybeMessage<::PlayerAttributeMessage>(Arena*);
template<> ::PlayerAttributeMessage_AmmoEntry_DoNotUse* Arena::CreateMaybeMessage<::PlayerAttributeMessage_AmmoEntry_DoNotUse>(Arena*);
template<> ::PlayerAttributeMessage_WeaponsEntry_DoNotUse* Arena::CreateMaybeMessage<::PlayerAttributeMessage_WeaponsEntry_DoNotUse>(Arena*);
template<> ::PlayerStateMessage* Arena::CreateMaybeMessage<::PlayerStateMessage>(Arena*);
template<> ::PlayerUpdateMessage* Arena::CreateMaybeMessage<::PlayerUpdateMessage>(Arena*);
template<> ::Vector3* Arena::CreateMaybeMessage<::Vector3>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum MessageType : int {
  HEARTBEAT = 0,
  PLAYER_UPDATE = 1,
  PLAYER_ATTRIBUTE = 2,
  PLAYER_STATE = 3,
  PLAYER_JOIN = 4,
  PLAYER_LEAVE = 5,
  MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool MessageType_IsValid(int value);
constexpr MessageType MessageType_MIN = HEARTBEAT;
constexpr MessageType MessageType_MAX = PLAYER_LEAVE;
constexpr int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor();
template<typename T>
inline const std::string& MessageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MessageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MessageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MessageType_descriptor(), enum_t_value);
}
inline bool MessageType_Parse(
    const std::string& name, MessageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
// ===================================================================

class Vector3 PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Vector3) */ {
 public:
  inline Vector3() : Vector3(nullptr) {};
  virtual ~Vector3();

  Vector3(const Vector3& from);
  Vector3(Vector3&& from) noexcept
    : Vector3() {
    *this = ::std::move(from);
  }

  inline Vector3& operator=(const Vector3& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector3& operator=(Vector3&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Vector3& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Vector3* internal_default_instance() {
    return reinterpret_cast<const Vector3*>(
               &_Vector3_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Vector3& a, Vector3& b) {
    a.Swap(&b);
  }
  inline void Swap(Vector3* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vector3* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Vector3* New() const final {
    return CreateMaybeMessage<Vector3>(nullptr);
  }

  Vector3* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Vector3>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Vector3& from);
  void MergeFrom(const Vector3& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector3* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Vector3";
  }
  protected:
  explicit Vector3(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_NetworkMessage_2eproto);
    return ::descriptor_table_NetworkMessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:Vector3)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  float z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_NetworkMessage_2eproto;
};
// -------------------------------------------------------------------

class PlayerAttributeMessage_AmmoEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PlayerAttributeMessage_AmmoEntry_DoNotUse, 
    std::string, ::PROTOBUF_NAMESPACE_ID::int32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PlayerAttributeMessage_AmmoEntry_DoNotUse, 
    std::string, ::PROTOBUF_NAMESPACE_ID::int32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    0 > SuperType;
  PlayerAttributeMessage_AmmoEntry_DoNotUse();
  PlayerAttributeMessage_AmmoEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const PlayerAttributeMessage_AmmoEntry_DoNotUse& other);
  static const PlayerAttributeMessage_AmmoEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const PlayerAttributeMessage_AmmoEntry_DoNotUse*>(&_PlayerAttributeMessage_AmmoEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "PlayerAttributeMessage.AmmoEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_NetworkMessage_2eproto);
    return ::descriptor_table_NetworkMessage_2eproto.file_level_metadata[1];
  }

  public:
};

// -------------------------------------------------------------------

class PlayerAttributeMessage_WeaponsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PlayerAttributeMessage_WeaponsEntry_DoNotUse, 
    std::string, ::PROTOBUF_NAMESPACE_ID::int32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PlayerAttributeMessage_WeaponsEntry_DoNotUse, 
    std::string, ::PROTOBUF_NAMESPACE_ID::int32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    0 > SuperType;
  PlayerAttributeMessage_WeaponsEntry_DoNotUse();
  PlayerAttributeMessage_WeaponsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const PlayerAttributeMessage_WeaponsEntry_DoNotUse& other);
  static const PlayerAttributeMessage_WeaponsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const PlayerAttributeMessage_WeaponsEntry_DoNotUse*>(&_PlayerAttributeMessage_WeaponsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "PlayerAttributeMessage.WeaponsEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_NetworkMessage_2eproto);
    return ::descriptor_table_NetworkMessage_2eproto.file_level_metadata[2];
  }

  public:
};

// -------------------------------------------------------------------

class PlayerAttributeMessage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PlayerAttributeMessage) */ {
 public:
  inline PlayerAttributeMessage() : PlayerAttributeMessage(nullptr) {};
  virtual ~PlayerAttributeMessage();

  PlayerAttributeMessage(const PlayerAttributeMessage& from);
  PlayerAttributeMessage(PlayerAttributeMessage&& from) noexcept
    : PlayerAttributeMessage() {
    *this = ::std::move(from);
  }

  inline PlayerAttributeMessage& operator=(const PlayerAttributeMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerAttributeMessage& operator=(PlayerAttributeMessage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PlayerAttributeMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlayerAttributeMessage* internal_default_instance() {
    return reinterpret_cast<const PlayerAttributeMessage*>(
               &_PlayerAttributeMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PlayerAttributeMessage& a, PlayerAttributeMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerAttributeMessage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerAttributeMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PlayerAttributeMessage* New() const final {
    return CreateMaybeMessage<PlayerAttributeMessage>(nullptr);
  }

  PlayerAttributeMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PlayerAttributeMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PlayerAttributeMessage& from);
  void MergeFrom(const PlayerAttributeMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerAttributeMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PlayerAttributeMessage";
  }
  protected:
  explicit PlayerAttributeMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_NetworkMessage_2eproto);
    return ::descriptor_table_NetworkMessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kAmmoFieldNumber = 4,
    kWeaponsFieldNumber = 5,
    kPlayerIdFieldNumber = 1,
    kHealthFieldNumber = 2,
    kMaxHealthFieldNumber = 3,
    kArmorFieldNumber = 6,
    kScoreFieldNumber = 7,
    kKillsFieldNumber = 8,
    kDeathsFieldNumber = 9,
  };
  // map<string, int32> ammo = 4;
  int ammo_size() const;
  private:
  int _internal_ammo_size() const;
  public:
  void clear_ammo();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_ammo() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_ammo();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >&
      ammo() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_ammo();

  // map<string, int32> weapons = 5;
  int weapons_size() const;
  private:
  int _internal_weapons_size() const;
  public:
  void clear_weapons();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_weapons() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_weapons();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >&
      weapons() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_weapons();

  // uint32 player_id = 1;
  void clear_player_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 player_id() const;
  void set_player_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_player_id() const;
  void _internal_set_player_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // float health = 2;
  void clear_health();
  float health() const;
  void set_health(float value);
  private:
  float _internal_health() const;
  void _internal_set_health(float value);
  public:

  // float max_health = 3;
  void clear_max_health();
  float max_health() const;
  void set_max_health(float value);
  private:
  float _internal_max_health() const;
  void _internal_set_max_health(float value);
  public:

  // float armor = 6;
  void clear_armor();
  float armor() const;
  void set_armor(float value);
  private:
  float _internal_armor() const;
  void _internal_set_armor(float value);
  public:

  // int32 score = 7;
  void clear_score();
  ::PROTOBUF_NAMESPACE_ID::int32 score() const;
  void set_score(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_score() const;
  void _internal_set_score(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 kills = 8;
  void clear_kills();
  ::PROTOBUF_NAMESPACE_ID::int32 kills() const;
  void set_kills(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_kills() const;
  void _internal_set_kills(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 deaths = 9;
  void clear_deaths();
  ::PROTOBUF_NAMESPACE_ID::int32 deaths() const;
  void set_deaths(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_deaths() const;
  void _internal_set_deaths(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:PlayerAttributeMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      PlayerAttributeMessage_AmmoEntry_DoNotUse,
      std::string, ::PROTOBUF_NAMESPACE_ID::int32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
      0 > ammo_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      PlayerAttributeMessage_WeaponsEntry_DoNotUse,
      std::string, ::PROTOBUF_NAMESPACE_ID::int32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
      0 > weapons_;
  ::PROTOBUF_NAMESPACE_ID::uint32 player_id_;
  float health_;
  float max_health_;
  float armor_;
  ::PROTOBUF_NAMESPACE_ID::int32 score_;
  ::PROTOBUF_NAMESPACE_ID::int32 kills_;
  ::PROTOBUF_NAMESPACE_ID::int32 deaths_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_NetworkMessage_2eproto;
};
// -------------------------------------------------------------------

class PlayerStateMessage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PlayerStateMessage) */ {
 public:
  inline PlayerStateMessage() : PlayerStateMessage(nullptr) {};
  virtual ~PlayerStateMessage();

  PlayerStateMessage(const PlayerStateMessage& from);
  PlayerStateMessage(PlayerStateMessage&& from) noexcept
    : PlayerStateMessage() {
    *this = ::std::move(from);
  }

  inline PlayerStateMessage& operator=(const PlayerStateMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerStateMessage& operator=(PlayerStateMessage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PlayerStateMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlayerStateMessage* internal_default_instance() {
    return reinterpret_cast<const PlayerStateMessage*>(
               &_PlayerStateMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(PlayerStateMessage& a, PlayerStateMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerStateMessage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerStateMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PlayerStateMessage* New() const final {
    return CreateMaybeMessage<PlayerStateMessage>(nullptr);
  }

  PlayerStateMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PlayerStateMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PlayerStateMessage& from);
  void MergeFrom(const PlayerStateMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerStateMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PlayerStateMessage";
  }
  protected:
  explicit PlayerStateMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_NetworkMessage_2eproto);
    return ::descriptor_table_NetworkMessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 2,
    kRotationFieldNumber = 3,
    kAttributesFieldNumber = 4,
    kPlayerIdFieldNumber = 1,
    kIsAliveFieldNumber = 5,
    kTeamIdFieldNumber = 6,
  };
  // .Vector3 position = 2;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::Vector3& position() const;
  ::Vector3* release_position();
  ::Vector3* mutable_position();
  void set_allocated_position(::Vector3* position);
  private:
  const ::Vector3& _internal_position() const;
  ::Vector3* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::Vector3* position);
  ::Vector3* unsafe_arena_release_position();

  // .Vector3 rotation = 3;
  bool has_rotation() const;
  private:
  bool _internal_has_rotation() const;
  public:
  void clear_rotation();
  const ::Vector3& rotation() const;
  ::Vector3* release_rotation();
  ::Vector3* mutable_rotation();
  void set_allocated_rotation(::Vector3* rotation);
  private:
  const ::Vector3& _internal_rotation() const;
  ::Vector3* _internal_mutable_rotation();
  public:
  void unsafe_arena_set_allocated_rotation(
      ::Vector3* rotation);
  ::Vector3* unsafe_arena_release_rotation();

  // .PlayerAttributeMessage attributes = 4;
  bool has_attributes() const;
  private:
  bool _internal_has_attributes() const;
  public:
  void clear_attributes();
  const ::PlayerAttributeMessage& attributes() const;
  ::PlayerAttributeMessage* release_attributes();
  ::PlayerAttributeMessage* mutable_attributes();
  void set_allocated_attributes(::PlayerAttributeMessage* attributes);
  private:
  const ::PlayerAttributeMessage& _internal_attributes() const;
  ::PlayerAttributeMessage* _internal_mutable_attributes();
  public:
  void unsafe_arena_set_allocated_attributes(
      ::PlayerAttributeMessage* attributes);
  ::PlayerAttributeMessage* unsafe_arena_release_attributes();

  // uint32 player_id = 1;
  void clear_player_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 player_id() const;
  void set_player_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_player_id() const;
  void _internal_set_player_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // bool is_alive = 5;
  void clear_is_alive();
  bool is_alive() const;
  void set_is_alive(bool value);
  private:
  bool _internal_is_alive() const;
  void _internal_set_is_alive(bool value);
  public:

  // uint32 team_id = 6;
  void clear_team_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 team_id() const;
  void set_team_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_team_id() const;
  void _internal_set_team_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:PlayerStateMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::Vector3* position_;
  ::Vector3* rotation_;
  ::PlayerAttributeMessage* attributes_;
  ::PROTOBUF_NAMESPACE_ID::uint32 player_id_;
  bool is_alive_;
  ::PROTOBUF_NAMESPACE_ID::uint32 team_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_NetworkMessage_2eproto;
};
// -------------------------------------------------------------------

class HeartbeatMessage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HeartbeatMessage) */ {
 public:
  inline HeartbeatMessage() : HeartbeatMessage(nullptr) {};
  virtual ~HeartbeatMessage();

  HeartbeatMessage(const HeartbeatMessage& from);
  HeartbeatMessage(HeartbeatMessage&& from) noexcept
    : HeartbeatMessage() {
    *this = ::std::move(from);
  }

  inline HeartbeatMessage& operator=(const HeartbeatMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline HeartbeatMessage& operator=(HeartbeatMessage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const HeartbeatMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HeartbeatMessage* internal_default_instance() {
    return reinterpret_cast<const HeartbeatMessage*>(
               &_HeartbeatMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(HeartbeatMessage& a, HeartbeatMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(HeartbeatMessage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HeartbeatMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline HeartbeatMessage* New() const final {
    return CreateMaybeMessage<HeartbeatMessage>(nullptr);
  }

  HeartbeatMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<HeartbeatMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const HeartbeatMessage& from);
  void MergeFrom(const HeartbeatMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HeartbeatMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HeartbeatMessage";
  }
  protected:
  explicit HeartbeatMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_NetworkMessage_2eproto);
    return ::descriptor_table_NetworkMessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:HeartbeatMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_NetworkMessage_2eproto;
};
// -------------------------------------------------------------------

class PlayerUpdateMessage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PlayerUpdateMessage) */ {
 public:
  inline PlayerUpdateMessage() : PlayerUpdateMessage(nullptr) {};
  virtual ~PlayerUpdateMessage();

  PlayerUpdateMessage(const PlayerUpdateMessage& from);
  PlayerUpdateMessage(PlayerUpdateMessage&& from) noexcept
    : PlayerUpdateMessage() {
    *this = ::std::move(from);
  }

  inline PlayerUpdateMessage& operator=(const PlayerUpdateMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerUpdateMessage& operator=(PlayerUpdateMessage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PlayerUpdateMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlayerUpdateMessage* internal_default_instance() {
    return reinterpret_cast<const PlayerUpdateMessage*>(
               &_PlayerUpdateMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(PlayerUpdateMessage& a, PlayerUpdateMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerUpdateMessage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerUpdateMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PlayerUpdateMessage* New() const final {
    return CreateMaybeMessage<PlayerUpdateMessage>(nullptr);
  }

  PlayerUpdateMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PlayerUpdateMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PlayerUpdateMessage& from);
  void MergeFrom(const PlayerUpdateMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerUpdateMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PlayerUpdateMessage";
  }
  protected:
  explicit PlayerUpdateMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_NetworkMessage_2eproto);
    return ::descriptor_table_NetworkMessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionXFieldNumber = 1,
    kPositionYFieldNumber = 2,
    kPositionZFieldNumber = 3,
    kRotationXFieldNumber = 4,
    kRotationYFieldNumber = 5,
    kRotationZFieldNumber = 6,
    kVelocityXFieldNumber = 7,
    kVelocityYFieldNumber = 8,
    kVelocityZFieldNumber = 9,
    kIsGroundedFieldNumber = 10,
    kHealthFieldNumber = 11,
  };
  // float position_x = 1;
  void clear_position_x();
  float position_x() const;
  void set_position_x(float value);
  private:
  float _internal_position_x() const;
  void _internal_set_position_x(float value);
  public:

  // float position_y = 2;
  void clear_position_y();
  float position_y() const;
  void set_position_y(float value);
  private:
  float _internal_position_y() const;
  void _internal_set_position_y(float value);
  public:

  // float position_z = 3;
  void clear_position_z();
  float position_z() const;
  void set_position_z(float value);
  private:
  float _internal_position_z() const;
  void _internal_set_position_z(float value);
  public:

  // float rotation_x = 4;
  void clear_rotation_x();
  float rotation_x() const;
  void set_rotation_x(float value);
  private:
  float _internal_rotation_x() const;
  void _internal_set_rotation_x(float value);
  public:

  // float rotation_y = 5;
  void clear_rotation_y();
  float rotation_y() const;
  void set_rotation_y(float value);
  private:
  float _internal_rotation_y() const;
  void _internal_set_rotation_y(float value);
  public:

  // float rotation_z = 6;
  void clear_rotation_z();
  float rotation_z() const;
  void set_rotation_z(float value);
  private:
  float _internal_rotation_z() const;
  void _internal_set_rotation_z(float value);
  public:

  // float velocity_x = 7;
  void clear_velocity_x();
  float velocity_x() const;
  void set_velocity_x(float value);
  private:
  float _internal_velocity_x() const;
  void _internal_set_velocity_x(float value);
  public:

  // float velocity_y = 8;
  void clear_velocity_y();
  float velocity_y() const;
  void set_velocity_y(float value);
  private:
  float _internal_velocity_y() const;
  void _internal_set_velocity_y(float value);
  public:

  // float velocity_z = 9;
  void clear_velocity_z();
  float velocity_z() const;
  void set_velocity_z(float value);
  private:
  float _internal_velocity_z() const;
  void _internal_set_velocity_z(float value);
  public:

  // bool is_grounded = 10;
  void clear_is_grounded();
  bool is_grounded() const;
  void set_is_grounded(bool value);
  private:
  bool _internal_is_grounded() const;
  void _internal_set_is_grounded(bool value);
  public:

  // float health = 11;
  void clear_health();
  float health() const;
  void set_health(float value);
  private:
  float _internal_health() const;
  void _internal_set_health(float value);
  public:

  // @@protoc_insertion_point(class_scope:PlayerUpdateMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float position_x_;
  float position_y_;
  float position_z_;
  float rotation_x_;
  float rotation_y_;
  float rotation_z_;
  float velocity_x_;
  float velocity_y_;
  float velocity_z_;
  bool is_grounded_;
  float health_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_NetworkMessage_2eproto;
};
// -------------------------------------------------------------------

class NetworkMessage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NetworkMessage) */ {
 public:
  inline NetworkMessage() : NetworkMessage(nullptr) {};
  virtual ~NetworkMessage();

  NetworkMessage(const NetworkMessage& from);
  NetworkMessage(NetworkMessage&& from) noexcept
    : NetworkMessage() {
    *this = ::std::move(from);
  }

  inline NetworkMessage& operator=(const NetworkMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline NetworkMessage& operator=(NetworkMessage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const NetworkMessage& default_instance();

  enum DataCase {
    kHeartbeat = 4,
    kPlayerUpdate = 5,
    kPlayerAttribute = 6,
    kPlayerState = 7,
    DATA_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NetworkMessage* internal_default_instance() {
    return reinterpret_cast<const NetworkMessage*>(
               &_NetworkMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(NetworkMessage& a, NetworkMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(NetworkMessage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NetworkMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NetworkMessage* New() const final {
    return CreateMaybeMessage<NetworkMessage>(nullptr);
  }

  NetworkMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NetworkMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const NetworkMessage& from);
  void MergeFrom(const NetworkMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NetworkMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "NetworkMessage";
  }
  protected:
  explicit NetworkMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_NetworkMessage_2eproto);
    return ::descriptor_table_NetworkMessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgIdFieldNumber = 1,
    kPlayerIdFieldNumber = 2,
    kTimestampFieldNumber = 3,
    kHeartbeatFieldNumber = 4,
    kPlayerUpdateFieldNumber = 5,
    kPlayerAttributeFieldNumber = 6,
    kPlayerStateFieldNumber = 7,
  };
  // .MessageType msg_id = 1;
  void clear_msg_id();
  ::MessageType msg_id() const;
  void set_msg_id(::MessageType value);
  private:
  ::MessageType _internal_msg_id() const;
  void _internal_set_msg_id(::MessageType value);
  public:

  // uint32 player_id = 2;
  void clear_player_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 player_id() const;
  void set_player_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_player_id() const;
  void _internal_set_player_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 timestamp = 3;
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::uint32 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // .HeartbeatMessage heartbeat = 4;
  bool has_heartbeat() const;
  private:
  bool _internal_has_heartbeat() const;
  public:
  void clear_heartbeat();
  const ::HeartbeatMessage& heartbeat() const;
  ::HeartbeatMessage* release_heartbeat();
  ::HeartbeatMessage* mutable_heartbeat();
  void set_allocated_heartbeat(::HeartbeatMessage* heartbeat);
  private:
  const ::HeartbeatMessage& _internal_heartbeat() const;
  ::HeartbeatMessage* _internal_mutable_heartbeat();
  public:
  void unsafe_arena_set_allocated_heartbeat(
      ::HeartbeatMessage* heartbeat);
  ::HeartbeatMessage* unsafe_arena_release_heartbeat();

  // .PlayerUpdateMessage player_update = 5;
  bool has_player_update() const;
  private:
  bool _internal_has_player_update() const;
  public:
  void clear_player_update();
  const ::PlayerUpdateMessage& player_update() const;
  ::PlayerUpdateMessage* release_player_update();
  ::PlayerUpdateMessage* mutable_player_update();
  void set_allocated_player_update(::PlayerUpdateMessage* player_update);
  private:
  const ::PlayerUpdateMessage& _internal_player_update() const;
  ::PlayerUpdateMessage* _internal_mutable_player_update();
  public:
  void unsafe_arena_set_allocated_player_update(
      ::PlayerUpdateMessage* player_update);
  ::PlayerUpdateMessage* unsafe_arena_release_player_update();

  // .PlayerAttributeMessage player_attribute = 6;
  bool has_player_attribute() const;
  private:
  bool _internal_has_player_attribute() const;
  public:
  void clear_player_attribute();
  const ::PlayerAttributeMessage& player_attribute() const;
  ::PlayerAttributeMessage* release_player_attribute();
  ::PlayerAttributeMessage* mutable_player_attribute();
  void set_allocated_player_attribute(::PlayerAttributeMessage* player_attribute);
  private:
  const ::PlayerAttributeMessage& _internal_player_attribute() const;
  ::PlayerAttributeMessage* _internal_mutable_player_attribute();
  public:
  void unsafe_arena_set_allocated_player_attribute(
      ::PlayerAttributeMessage* player_attribute);
  ::PlayerAttributeMessage* unsafe_arena_release_player_attribute();

  // .PlayerStateMessage player_state = 7;
  bool has_player_state() const;
  private:
  bool _internal_has_player_state() const;
  public:
  void clear_player_state();
  const ::PlayerStateMessage& player_state() const;
  ::PlayerStateMessage* release_player_state();
  ::PlayerStateMessage* mutable_player_state();
  void set_allocated_player_state(::PlayerStateMessage* player_state);
  private:
  const ::PlayerStateMessage& _internal_player_state() const;
  ::PlayerStateMessage* _internal_mutable_player_state();
  public:
  void unsafe_arena_set_allocated_player_state(
      ::PlayerStateMessage* player_state);
  ::PlayerStateMessage* unsafe_arena_release_player_state();

  void clear_data();
  DataCase data_case() const;
  // @@protoc_insertion_point(class_scope:NetworkMessage)
 private:
  class _Internal;
  void set_has_heartbeat();
  void set_has_player_update();
  void set_has_player_attribute();
  void set_has_player_state();

  inline bool has_data() const;
  inline void clear_has_data();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int msg_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 player_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 timestamp_;
  union DataUnion {
    DataUnion() {}
    ::HeartbeatMessage* heartbeat_;
    ::PlayerUpdateMessage* player_update_;
    ::PlayerAttributeMessage* player_attribute_;
    ::PlayerStateMessage* player_state_;
  } data_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_NetworkMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Vector3

// float x = 1;
inline void Vector3::clear_x() {
  x_ = 0;
}
inline float Vector3::_internal_x() const {
  return x_;
}
inline float Vector3::x() const {
  // @@protoc_insertion_point(field_get:Vector3.x)
  return _internal_x();
}
inline void Vector3::_internal_set_x(float value) {
  
  x_ = value;
}
inline void Vector3::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Vector3.x)
}

// float y = 2;
inline void Vector3::clear_y() {
  y_ = 0;
}
inline float Vector3::_internal_y() const {
  return y_;
}
inline float Vector3::y() const {
  // @@protoc_insertion_point(field_get:Vector3.y)
  return _internal_y();
}
inline void Vector3::_internal_set_y(float value) {
  
  y_ = value;
}
inline void Vector3::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Vector3.y)
}

// float z = 3;
inline void Vector3::clear_z() {
  z_ = 0;
}
inline float Vector3::_internal_z() const {
  return z_;
}
inline float Vector3::z() const {
  // @@protoc_insertion_point(field_get:Vector3.z)
  return _internal_z();
}
inline void Vector3::_internal_set_z(float value) {
  
  z_ = value;
}
inline void Vector3::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Vector3.z)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// PlayerAttributeMessage

// uint32 player_id = 1;
inline void PlayerAttributeMessage::clear_player_id() {
  player_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PlayerAttributeMessage::_internal_player_id() const {
  return player_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PlayerAttributeMessage::player_id() const {
  // @@protoc_insertion_point(field_get:PlayerAttributeMessage.player_id)
  return _internal_player_id();
}
inline void PlayerAttributeMessage::_internal_set_player_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  player_id_ = value;
}
inline void PlayerAttributeMessage::set_player_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:PlayerAttributeMessage.player_id)
}

// float health = 2;
inline void PlayerAttributeMessage::clear_health() {
  health_ = 0;
}
inline float PlayerAttributeMessage::_internal_health() const {
  return health_;
}
inline float PlayerAttributeMessage::health() const {
  // @@protoc_insertion_point(field_get:PlayerAttributeMessage.health)
  return _internal_health();
}
inline void PlayerAttributeMessage::_internal_set_health(float value) {
  
  health_ = value;
}
inline void PlayerAttributeMessage::set_health(float value) {
  _internal_set_health(value);
  // @@protoc_insertion_point(field_set:PlayerAttributeMessage.health)
}

// float max_health = 3;
inline void PlayerAttributeMessage::clear_max_health() {
  max_health_ = 0;
}
inline float PlayerAttributeMessage::_internal_max_health() const {
  return max_health_;
}
inline float PlayerAttributeMessage::max_health() const {
  // @@protoc_insertion_point(field_get:PlayerAttributeMessage.max_health)
  return _internal_max_health();
}
inline void PlayerAttributeMessage::_internal_set_max_health(float value) {
  
  max_health_ = value;
}
inline void PlayerAttributeMessage::set_max_health(float value) {
  _internal_set_max_health(value);
  // @@protoc_insertion_point(field_set:PlayerAttributeMessage.max_health)
}

// map<string, int32> ammo = 4;
inline int PlayerAttributeMessage::_internal_ammo_size() const {
  return ammo_.size();
}
inline int PlayerAttributeMessage::ammo_size() const {
  return _internal_ammo_size();
}
inline void PlayerAttributeMessage::clear_ammo() {
  ammo_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >&
PlayerAttributeMessage::_internal_ammo() const {
  return ammo_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >&
PlayerAttributeMessage::ammo() const {
  // @@protoc_insertion_point(field_map:PlayerAttributeMessage.ammo)
  return _internal_ammo();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >*
PlayerAttributeMessage::_internal_mutable_ammo() {
  return ammo_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >*
PlayerAttributeMessage::mutable_ammo() {
  // @@protoc_insertion_point(field_mutable_map:PlayerAttributeMessage.ammo)
  return _internal_mutable_ammo();
}

// map<string, int32> weapons = 5;
inline int PlayerAttributeMessage::_internal_weapons_size() const {
  return weapons_.size();
}
inline int PlayerAttributeMessage::weapons_size() const {
  return _internal_weapons_size();
}
inline void PlayerAttributeMessage::clear_weapons() {
  weapons_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >&
PlayerAttributeMessage::_internal_weapons() const {
  return weapons_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >&
PlayerAttributeMessage::weapons() const {
  // @@protoc_insertion_point(field_map:PlayerAttributeMessage.weapons)
  return _internal_weapons();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >*
PlayerAttributeMessage::_internal_mutable_weapons() {
  return weapons_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >*
PlayerAttributeMessage::mutable_weapons() {
  // @@protoc_insertion_point(field_mutable_map:PlayerAttributeMessage.weapons)
  return _internal_mutable_weapons();
}

// float armor = 6;
inline void PlayerAttributeMessage::clear_armor() {
  armor_ = 0;
}
inline float PlayerAttributeMessage::_internal_armor() const {
  return armor_;
}
inline float PlayerAttributeMessage::armor() const {
  // @@protoc_insertion_point(field_get:PlayerAttributeMessage.armor)
  return _internal_armor();
}
inline void PlayerAttributeMessage::_internal_set_armor(float value) {
  
  armor_ = value;
}
inline void PlayerAttributeMessage::set_armor(float value) {
  _internal_set_armor(value);
  // @@protoc_insertion_point(field_set:PlayerAttributeMessage.armor)
}

// int32 score = 7;
inline void PlayerAttributeMessage::clear_score() {
  score_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PlayerAttributeMessage::_internal_score() const {
  return score_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PlayerAttributeMessage::score() const {
  // @@protoc_insertion_point(field_get:PlayerAttributeMessage.score)
  return _internal_score();
}
inline void PlayerAttributeMessage::_internal_set_score(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  score_ = value;
}
inline void PlayerAttributeMessage::set_score(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_score(value);
  // @@protoc_insertion_point(field_set:PlayerAttributeMessage.score)
}

// int32 kills = 8;
inline void PlayerAttributeMessage::clear_kills() {
  kills_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PlayerAttributeMessage::_internal_kills() const {
  return kills_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PlayerAttributeMessage::kills() const {
  // @@protoc_insertion_point(field_get:PlayerAttributeMessage.kills)
  return _internal_kills();
}
inline void PlayerAttributeMessage::_internal_set_kills(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  kills_ = value;
}
inline void PlayerAttributeMessage::set_kills(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_kills(value);
  // @@protoc_insertion_point(field_set:PlayerAttributeMessage.kills)
}

// int32 deaths = 9;
inline void PlayerAttributeMessage::clear_deaths() {
  deaths_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PlayerAttributeMessage::_internal_deaths() const {
  return deaths_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PlayerAttributeMessage::deaths() const {
  // @@protoc_insertion_point(field_get:PlayerAttributeMessage.deaths)
  return _internal_deaths();
}
inline void PlayerAttributeMessage::_internal_set_deaths(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  deaths_ = value;
}
inline void PlayerAttributeMessage::set_deaths(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_deaths(value);
  // @@protoc_insertion_point(field_set:PlayerAttributeMessage.deaths)
}

// -------------------------------------------------------------------

// PlayerStateMessage

// uint32 player_id = 1;
inline void PlayerStateMessage::clear_player_id() {
  player_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PlayerStateMessage::_internal_player_id() const {
  return player_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PlayerStateMessage::player_id() const {
  // @@protoc_insertion_point(field_get:PlayerStateMessage.player_id)
  return _internal_player_id();
}
inline void PlayerStateMessage::_internal_set_player_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  player_id_ = value;
}
inline void PlayerStateMessage::set_player_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:PlayerStateMessage.player_id)
}

// .Vector3 position = 2;
inline bool PlayerStateMessage::_internal_has_position() const {
  return this != internal_default_instance() && position_ != nullptr;
}
inline bool PlayerStateMessage::has_position() const {
  return _internal_has_position();
}
inline void PlayerStateMessage::clear_position() {
  if (GetArena() == nullptr && position_ != nullptr) {
    delete position_;
  }
  position_ = nullptr;
}
inline const ::Vector3& PlayerStateMessage::_internal_position() const {
  const ::Vector3* p = position_;
  return p != nullptr ? *p : *reinterpret_cast<const ::Vector3*>(
      &::_Vector3_default_instance_);
}
inline const ::Vector3& PlayerStateMessage::position() const {
  // @@protoc_insertion_point(field_get:PlayerStateMessage.position)
  return _internal_position();
}
inline void PlayerStateMessage::unsafe_arena_set_allocated_position(
    ::Vector3* position) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PlayerStateMessage.position)
}
inline ::Vector3* PlayerStateMessage::release_position() {
  auto temp = unsafe_arena_release_position();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Vector3* PlayerStateMessage::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:PlayerStateMessage.position)
  
  ::Vector3* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::Vector3* PlayerStateMessage::_internal_mutable_position() {
  
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::Vector3>(GetArena());
    position_ = p;
  }
  return position_;
}
inline ::Vector3* PlayerStateMessage::mutable_position() {
  // @@protoc_insertion_point(field_mutable:PlayerStateMessage.position)
  return _internal_mutable_position();
}
inline void PlayerStateMessage::set_allocated_position(::Vector3* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete position_;
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(position);
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:PlayerStateMessage.position)
}

// .Vector3 rotation = 3;
inline bool PlayerStateMessage::_internal_has_rotation() const {
  return this != internal_default_instance() && rotation_ != nullptr;
}
inline bool PlayerStateMessage::has_rotation() const {
  return _internal_has_rotation();
}
inline void PlayerStateMessage::clear_rotation() {
  if (GetArena() == nullptr && rotation_ != nullptr) {
    delete rotation_;
  }
  rotation_ = nullptr;
}
inline const ::Vector3& PlayerStateMessage::_internal_rotation() const {
  const ::Vector3* p = rotation_;
  return p != nullptr ? *p : *reinterpret_cast<const ::Vector3*>(
      &::_Vector3_default_instance_);
}
inline const ::Vector3& PlayerStateMessage::rotation() const {
  // @@protoc_insertion_point(field_get:PlayerStateMessage.rotation)
  return _internal_rotation();
}
inline void PlayerStateMessage::unsafe_arena_set_allocated_rotation(
    ::Vector3* rotation) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(rotation_);
  }
  rotation_ = rotation;
  if (rotation) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PlayerStateMessage.rotation)
}
inline ::Vector3* PlayerStateMessage::release_rotation() {
  auto temp = unsafe_arena_release_rotation();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Vector3* PlayerStateMessage::unsafe_arena_release_rotation() {
  // @@protoc_insertion_point(field_release:PlayerStateMessage.rotation)
  
  ::Vector3* temp = rotation_;
  rotation_ = nullptr;
  return temp;
}
inline ::Vector3* PlayerStateMessage::_internal_mutable_rotation() {
  
  if (rotation_ == nullptr) {
    auto* p = CreateMaybeMessage<::Vector3>(GetArena());
    rotation_ = p;
  }
  return rotation_;
}
inline ::Vector3* PlayerStateMessage::mutable_rotation() {
  // @@protoc_insertion_point(field_mutable:PlayerStateMessage.rotation)
  return _internal_mutable_rotation();
}
inline void PlayerStateMessage::set_allocated_rotation(::Vector3* rotation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete rotation_;
  }
  if (rotation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(rotation);
    if (message_arena != submessage_arena) {
      rotation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rotation, submessage_arena);
    }
    
  } else {
    
  }
  rotation_ = rotation;
  // @@protoc_insertion_point(field_set_allocated:PlayerStateMessage.rotation)
}

// .PlayerAttributeMessage attributes = 4;
inline bool PlayerStateMessage::_internal_has_attributes() const {
  return this != internal_default_instance() && attributes_ != nullptr;
}
inline bool PlayerStateMessage::has_attributes() const {
  return _internal_has_attributes();
}
inline void PlayerStateMessage::clear_attributes() {
  if (GetArena() == nullptr && attributes_ != nullptr) {
    delete attributes_;
  }
  attributes_ = nullptr;
}
inline const ::PlayerAttributeMessage& PlayerStateMessage::_internal_attributes() const {
  const ::PlayerAttributeMessage* p = attributes_;
  return p != nullptr ? *p : *reinterpret_cast<const ::PlayerAttributeMessage*>(
      &::_PlayerAttributeMessage_default_instance_);
}
inline const ::PlayerAttributeMessage& PlayerStateMessage::attributes() const {
  // @@protoc_insertion_point(field_get:PlayerStateMessage.attributes)
  return _internal_attributes();
}
inline void PlayerStateMessage::unsafe_arena_set_allocated_attributes(
    ::PlayerAttributeMessage* attributes) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(attributes_);
  }
  attributes_ = attributes;
  if (attributes) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PlayerStateMessage.attributes)
}
inline ::PlayerAttributeMessage* PlayerStateMessage::release_attributes() {
  auto temp = unsafe_arena_release_attributes();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::PlayerAttributeMessage* PlayerStateMessage::unsafe_arena_release_attributes() {
  // @@protoc_insertion_point(field_release:PlayerStateMessage.attributes)
  
  ::PlayerAttributeMessage* temp = attributes_;
  attributes_ = nullptr;
  return temp;
}
inline ::PlayerAttributeMessage* PlayerStateMessage::_internal_mutable_attributes() {
  
  if (attributes_ == nullptr) {
    auto* p = CreateMaybeMessage<::PlayerAttributeMessage>(GetArena());
    attributes_ = p;
  }
  return attributes_;
}
inline ::PlayerAttributeMessage* PlayerStateMessage::mutable_attributes() {
  // @@protoc_insertion_point(field_mutable:PlayerStateMessage.attributes)
  return _internal_mutable_attributes();
}
inline void PlayerStateMessage::set_allocated_attributes(::PlayerAttributeMessage* attributes) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete attributes_;
  }
  if (attributes) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(attributes);
    if (message_arena != submessage_arena) {
      attributes = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, attributes, submessage_arena);
    }
    
  } else {
    
  }
  attributes_ = attributes;
  // @@protoc_insertion_point(field_set_allocated:PlayerStateMessage.attributes)
}

// bool is_alive = 5;
inline void PlayerStateMessage::clear_is_alive() {
  is_alive_ = false;
}
inline bool PlayerStateMessage::_internal_is_alive() const {
  return is_alive_;
}
inline bool PlayerStateMessage::is_alive() const {
  // @@protoc_insertion_point(field_get:PlayerStateMessage.is_alive)
  return _internal_is_alive();
}
inline void PlayerStateMessage::_internal_set_is_alive(bool value) {
  
  is_alive_ = value;
}
inline void PlayerStateMessage::set_is_alive(bool value) {
  _internal_set_is_alive(value);
  // @@protoc_insertion_point(field_set:PlayerStateMessage.is_alive)
}

// uint32 team_id = 6;
inline void PlayerStateMessage::clear_team_id() {
  team_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PlayerStateMessage::_internal_team_id() const {
  return team_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PlayerStateMessage::team_id() const {
  // @@protoc_insertion_point(field_get:PlayerStateMessage.team_id)
  return _internal_team_id();
}
inline void PlayerStateMessage::_internal_set_team_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  team_id_ = value;
}
inline void PlayerStateMessage::set_team_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_team_id(value);
  // @@protoc_insertion_point(field_set:PlayerStateMessage.team_id)
}

// -------------------------------------------------------------------

// HeartbeatMessage

// -------------------------------------------------------------------

// PlayerUpdateMessage

// float position_x = 1;
inline void PlayerUpdateMessage::clear_position_x() {
  position_x_ = 0;
}
inline float PlayerUpdateMessage::_internal_position_x() const {
  return position_x_;
}
inline float PlayerUpdateMessage::position_x() const {
  // @@protoc_insertion_point(field_get:PlayerUpdateMessage.position_x)
  return _internal_position_x();
}
inline void PlayerUpdateMessage::_internal_set_position_x(float value) {
  
  position_x_ = value;
}
inline void PlayerUpdateMessage::set_position_x(float value) {
  _internal_set_position_x(value);
  // @@protoc_insertion_point(field_set:PlayerUpdateMessage.position_x)
}

// float position_y = 2;
inline void PlayerUpdateMessage::clear_position_y() {
  position_y_ = 0;
}
inline float PlayerUpdateMessage::_internal_position_y() const {
  return position_y_;
}
inline float PlayerUpdateMessage::position_y() const {
  // @@protoc_insertion_point(field_get:PlayerUpdateMessage.position_y)
  return _internal_position_y();
}
inline void PlayerUpdateMessage::_internal_set_position_y(float value) {
  
  position_y_ = value;
}
inline void PlayerUpdateMessage::set_position_y(float value) {
  _internal_set_position_y(value);
  // @@protoc_insertion_point(field_set:PlayerUpdateMessage.position_y)
}

// float position_z = 3;
inline void PlayerUpdateMessage::clear_position_z() {
  position_z_ = 0;
}
inline float PlayerUpdateMessage::_internal_position_z() const {
  return position_z_;
}
inline float PlayerUpdateMessage::position_z() const {
  // @@protoc_insertion_point(field_get:PlayerUpdateMessage.position_z)
  return _internal_position_z();
}
inline void PlayerUpdateMessage::_internal_set_position_z(float value) {
  
  position_z_ = value;
}
inline void PlayerUpdateMessage::set_position_z(float value) {
  _internal_set_position_z(value);
  // @@protoc_insertion_point(field_set:PlayerUpdateMessage.position_z)
}

// float rotation_x = 4;
inline void PlayerUpdateMessage::clear_rotation_x() {
  rotation_x_ = 0;
}
inline float PlayerUpdateMessage::_internal_rotation_x() const {
  return rotation_x_;
}
inline float PlayerUpdateMessage::rotation_x() const {
  // @@protoc_insertion_point(field_get:PlayerUpdateMessage.rotation_x)
  return _internal_rotation_x();
}
inline void PlayerUpdateMessage::_internal_set_rotation_x(float value) {
  
  rotation_x_ = value;
}
inline void PlayerUpdateMessage::set_rotation_x(float value) {
  _internal_set_rotation_x(value);
  // @@protoc_insertion_point(field_set:PlayerUpdateMessage.rotation_x)
}

// float rotation_y = 5;
inline void PlayerUpdateMessage::clear_rotation_y() {
  rotation_y_ = 0;
}
inline float PlayerUpdateMessage::_internal_rotation_y() const {
  return rotation_y_;
}
inline float PlayerUpdateMessage::rotation_y() const {
  // @@protoc_insertion_point(field_get:PlayerUpdateMessage.rotation_y)
  return _internal_rotation_y();
}
inline void PlayerUpdateMessage::_internal_set_rotation_y(float value) {
  
  rotation_y_ = value;
}
inline void PlayerUpdateMessage::set_rotation_y(float value) {
  _internal_set_rotation_y(value);
  // @@protoc_insertion_point(field_set:PlayerUpdateMessage.rotation_y)
}

// float rotation_z = 6;
inline void PlayerUpdateMessage::clear_rotation_z() {
  rotation_z_ = 0;
}
inline float PlayerUpdateMessage::_internal_rotation_z() const {
  return rotation_z_;
}
inline float PlayerUpdateMessage::rotation_z() const {
  // @@protoc_insertion_point(field_get:PlayerUpdateMessage.rotation_z)
  return _internal_rotation_z();
}
inline void PlayerUpdateMessage::_internal_set_rotation_z(float value) {
  
  rotation_z_ = value;
}
inline void PlayerUpdateMessage::set_rotation_z(float value) {
  _internal_set_rotation_z(value);
  // @@protoc_insertion_point(field_set:PlayerUpdateMessage.rotation_z)
}

// float velocity_x = 7;
inline void PlayerUpdateMessage::clear_velocity_x() {
  velocity_x_ = 0;
}
inline float PlayerUpdateMessage::_internal_velocity_x() const {
  return velocity_x_;
}
inline float PlayerUpdateMessage::velocity_x() const {
  // @@protoc_insertion_point(field_get:PlayerUpdateMessage.velocity_x)
  return _internal_velocity_x();
}
inline void PlayerUpdateMessage::_internal_set_velocity_x(float value) {
  
  velocity_x_ = value;
}
inline void PlayerUpdateMessage::set_velocity_x(float value) {
  _internal_set_velocity_x(value);
  // @@protoc_insertion_point(field_set:PlayerUpdateMessage.velocity_x)
}

// float velocity_y = 8;
inline void PlayerUpdateMessage::clear_velocity_y() {
  velocity_y_ = 0;
}
inline float PlayerUpdateMessage::_internal_velocity_y() const {
  return velocity_y_;
}
inline float PlayerUpdateMessage::velocity_y() const {
  // @@protoc_insertion_point(field_get:PlayerUpdateMessage.velocity_y)
  return _internal_velocity_y();
}
inline void PlayerUpdateMessage::_internal_set_velocity_y(float value) {
  
  velocity_y_ = value;
}
inline void PlayerUpdateMessage::set_velocity_y(float value) {
  _internal_set_velocity_y(value);
  // @@protoc_insertion_point(field_set:PlayerUpdateMessage.velocity_y)
}

// float velocity_z = 9;
inline void PlayerUpdateMessage::clear_velocity_z() {
  velocity_z_ = 0;
}
inline float PlayerUpdateMessage::_internal_velocity_z() const {
  return velocity_z_;
}
inline float PlayerUpdateMessage::velocity_z() const {
  // @@protoc_insertion_point(field_get:PlayerUpdateMessage.velocity_z)
  return _internal_velocity_z();
}
inline void PlayerUpdateMessage::_internal_set_velocity_z(float value) {
  
  velocity_z_ = value;
}
inline void PlayerUpdateMessage::set_velocity_z(float value) {
  _internal_set_velocity_z(value);
  // @@protoc_insertion_point(field_set:PlayerUpdateMessage.velocity_z)
}

// bool is_grounded = 10;
inline void PlayerUpdateMessage::clear_is_grounded() {
  is_grounded_ = false;
}
inline bool PlayerUpdateMessage::_internal_is_grounded() const {
  return is_grounded_;
}
inline bool PlayerUpdateMessage::is_grounded() const {
  // @@protoc_insertion_point(field_get:PlayerUpdateMessage.is_grounded)
  return _internal_is_grounded();
}
inline void PlayerUpdateMessage::_internal_set_is_grounded(bool value) {
  
  is_grounded_ = value;
}
inline void PlayerUpdateMessage::set_is_grounded(bool value) {
  _internal_set_is_grounded(value);
  // @@protoc_insertion_point(field_set:PlayerUpdateMessage.is_grounded)
}

// float health = 11;
inline void PlayerUpdateMessage::clear_health() {
  health_ = 0;
}
inline float PlayerUpdateMessage::_internal_health() const {
  return health_;
}
inline float PlayerUpdateMessage::health() const {
  // @@protoc_insertion_point(field_get:PlayerUpdateMessage.health)
  return _internal_health();
}
inline void PlayerUpdateMessage::_internal_set_health(float value) {
  
  health_ = value;
}
inline void PlayerUpdateMessage::set_health(float value) {
  _internal_set_health(value);
  // @@protoc_insertion_point(field_set:PlayerUpdateMessage.health)
}

// -------------------------------------------------------------------

// NetworkMessage

// .MessageType msg_id = 1;
inline void NetworkMessage::clear_msg_id() {
  msg_id_ = 0;
}
inline ::MessageType NetworkMessage::_internal_msg_id() const {
  return static_cast< ::MessageType >(msg_id_);
}
inline ::MessageType NetworkMessage::msg_id() const {
  // @@protoc_insertion_point(field_get:NetworkMessage.msg_id)
  return _internal_msg_id();
}
inline void NetworkMessage::_internal_set_msg_id(::MessageType value) {
  
  msg_id_ = value;
}
inline void NetworkMessage::set_msg_id(::MessageType value) {
  _internal_set_msg_id(value);
  // @@protoc_insertion_point(field_set:NetworkMessage.msg_id)
}

// uint32 player_id = 2;
inline void NetworkMessage::clear_player_id() {
  player_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NetworkMessage::_internal_player_id() const {
  return player_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NetworkMessage::player_id() const {
  // @@protoc_insertion_point(field_get:NetworkMessage.player_id)
  return _internal_player_id();
}
inline void NetworkMessage::_internal_set_player_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  player_id_ = value;
}
inline void NetworkMessage::set_player_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:NetworkMessage.player_id)
}

// uint32 timestamp = 3;
inline void NetworkMessage::clear_timestamp() {
  timestamp_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NetworkMessage::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NetworkMessage::timestamp() const {
  // @@protoc_insertion_point(field_get:NetworkMessage.timestamp)
  return _internal_timestamp();
}
inline void NetworkMessage::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  timestamp_ = value;
}
inline void NetworkMessage::set_timestamp(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:NetworkMessage.timestamp)
}

// .HeartbeatMessage heartbeat = 4;
inline bool NetworkMessage::_internal_has_heartbeat() const {
  return data_case() == kHeartbeat;
}
inline bool NetworkMessage::has_heartbeat() const {
  return _internal_has_heartbeat();
}
inline void NetworkMessage::set_has_heartbeat() {
  _oneof_case_[0] = kHeartbeat;
}
inline void NetworkMessage::clear_heartbeat() {
  if (_internal_has_heartbeat()) {
    if (GetArena() == nullptr) {
      delete data_.heartbeat_;
    }
    clear_has_data();
  }
}
inline ::HeartbeatMessage* NetworkMessage::release_heartbeat() {
  // @@protoc_insertion_point(field_release:NetworkMessage.heartbeat)
  if (_internal_has_heartbeat()) {
    clear_has_data();
      ::HeartbeatMessage* temp = data_.heartbeat_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    data_.heartbeat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::HeartbeatMessage& NetworkMessage::_internal_heartbeat() const {
  return _internal_has_heartbeat()
      ? *data_.heartbeat_
      : *reinterpret_cast< ::HeartbeatMessage*>(&::_HeartbeatMessage_default_instance_);
}
inline const ::HeartbeatMessage& NetworkMessage::heartbeat() const {
  // @@protoc_insertion_point(field_get:NetworkMessage.heartbeat)
  return _internal_heartbeat();
}
inline ::HeartbeatMessage* NetworkMessage::unsafe_arena_release_heartbeat() {
  // @@protoc_insertion_point(field_unsafe_arena_release:NetworkMessage.heartbeat)
  if (_internal_has_heartbeat()) {
    clear_has_data();
    ::HeartbeatMessage* temp = data_.heartbeat_;
    data_.heartbeat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void NetworkMessage::unsafe_arena_set_allocated_heartbeat(::HeartbeatMessage* heartbeat) {
  clear_data();
  if (heartbeat) {
    set_has_heartbeat();
    data_.heartbeat_ = heartbeat;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NetworkMessage.heartbeat)
}
inline ::HeartbeatMessage* NetworkMessage::_internal_mutable_heartbeat() {
  if (!_internal_has_heartbeat()) {
    clear_data();
    set_has_heartbeat();
    data_.heartbeat_ = CreateMaybeMessage< ::HeartbeatMessage >(GetArena());
  }
  return data_.heartbeat_;
}
inline ::HeartbeatMessage* NetworkMessage::mutable_heartbeat() {
  // @@protoc_insertion_point(field_mutable:NetworkMessage.heartbeat)
  return _internal_mutable_heartbeat();
}

// .PlayerUpdateMessage player_update = 5;
inline bool NetworkMessage::_internal_has_player_update() const {
  return data_case() == kPlayerUpdate;
}
inline bool NetworkMessage::has_player_update() const {
  return _internal_has_player_update();
}
inline void NetworkMessage::set_has_player_update() {
  _oneof_case_[0] = kPlayerUpdate;
}
inline void NetworkMessage::clear_player_update() {
  if (_internal_has_player_update()) {
    if (GetArena() == nullptr) {
      delete data_.player_update_;
    }
    clear_has_data();
  }
}
inline ::PlayerUpdateMessage* NetworkMessage::release_player_update() {
  // @@protoc_insertion_point(field_release:NetworkMessage.player_update)
  if (_internal_has_player_update()) {
    clear_has_data();
      ::PlayerUpdateMessage* temp = data_.player_update_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    data_.player_update_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PlayerUpdateMessage& NetworkMessage::_internal_player_update() const {
  return _internal_has_player_update()
      ? *data_.player_update_
      : *reinterpret_cast< ::PlayerUpdateMessage*>(&::_PlayerUpdateMessage_default_instance_);
}
inline const ::PlayerUpdateMessage& NetworkMessage::player_update() const {
  // @@protoc_insertion_point(field_get:NetworkMessage.player_update)
  return _internal_player_update();
}
inline ::PlayerUpdateMessage* NetworkMessage::unsafe_arena_release_player_update() {
  // @@protoc_insertion_point(field_unsafe_arena_release:NetworkMessage.player_update)
  if (_internal_has_player_update()) {
    clear_has_data();
    ::PlayerUpdateMessage* temp = data_.player_update_;
    data_.player_update_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void NetworkMessage::unsafe_arena_set_allocated_player_update(::PlayerUpdateMessage* player_update) {
  clear_data();
  if (player_update) {
    set_has_player_update();
    data_.player_update_ = player_update;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NetworkMessage.player_update)
}
inline ::PlayerUpdateMessage* NetworkMessage::_internal_mutable_player_update() {
  if (!_internal_has_player_update()) {
    clear_data();
    set_has_player_update();
    data_.player_update_ = CreateMaybeMessage< ::PlayerUpdateMessage >(GetArena());
  }
  return data_.player_update_;
}
inline ::PlayerUpdateMessage* NetworkMessage::mutable_player_update() {
  // @@protoc_insertion_point(field_mutable:NetworkMessage.player_update)
  return _internal_mutable_player_update();
}

// .PlayerAttributeMessage player_attribute = 6;
inline bool NetworkMessage::_internal_has_player_attribute() const {
  return data_case() == kPlayerAttribute;
}
inline bool NetworkMessage::has_player_attribute() const {
  return _internal_has_player_attribute();
}
inline void NetworkMessage::set_has_player_attribute() {
  _oneof_case_[0] = kPlayerAttribute;
}
inline void NetworkMessage::clear_player_attribute() {
  if (_internal_has_player_attribute()) {
    if (GetArena() == nullptr) {
      delete data_.player_attribute_;
    }
    clear_has_data();
  }
}
inline ::PlayerAttributeMessage* NetworkMessage::release_player_attribute() {
  // @@protoc_insertion_point(field_release:NetworkMessage.player_attribute)
  if (_internal_has_player_attribute()) {
    clear_has_data();
      ::PlayerAttributeMessage* temp = data_.player_attribute_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    data_.player_attribute_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PlayerAttributeMessage& NetworkMessage::_internal_player_attribute() const {
  return _internal_has_player_attribute()
      ? *data_.player_attribute_
      : *reinterpret_cast< ::PlayerAttributeMessage*>(&::_PlayerAttributeMessage_default_instance_);
}
inline const ::PlayerAttributeMessage& NetworkMessage::player_attribute() const {
  // @@protoc_insertion_point(field_get:NetworkMessage.player_attribute)
  return _internal_player_attribute();
}
inline ::PlayerAttributeMessage* NetworkMessage::unsafe_arena_release_player_attribute() {
  // @@protoc_insertion_point(field_unsafe_arena_release:NetworkMessage.player_attribute)
  if (_internal_has_player_attribute()) {
    clear_has_data();
    ::PlayerAttributeMessage* temp = data_.player_attribute_;
    data_.player_attribute_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void NetworkMessage::unsafe_arena_set_allocated_player_attribute(::PlayerAttributeMessage* player_attribute) {
  clear_data();
  if (player_attribute) {
    set_has_player_attribute();
    data_.player_attribute_ = player_attribute;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NetworkMessage.player_attribute)
}
inline ::PlayerAttributeMessage* NetworkMessage::_internal_mutable_player_attribute() {
  if (!_internal_has_player_attribute()) {
    clear_data();
    set_has_player_attribute();
    data_.player_attribute_ = CreateMaybeMessage< ::PlayerAttributeMessage >(GetArena());
  }
  return data_.player_attribute_;
}
inline ::PlayerAttributeMessage* NetworkMessage::mutable_player_attribute() {
  // @@protoc_insertion_point(field_mutable:NetworkMessage.player_attribute)
  return _internal_mutable_player_attribute();
}

// .PlayerStateMessage player_state = 7;
inline bool NetworkMessage::_internal_has_player_state() const {
  return data_case() == kPlayerState;
}
inline bool NetworkMessage::has_player_state() const {
  return _internal_has_player_state();
}
inline void NetworkMessage::set_has_player_state() {
  _oneof_case_[0] = kPlayerState;
}
inline void NetworkMessage::clear_player_state() {
  if (_internal_has_player_state()) {
    if (GetArena() == nullptr) {
      delete data_.player_state_;
    }
    clear_has_data();
  }
}
inline ::PlayerStateMessage* NetworkMessage::release_player_state() {
  // @@protoc_insertion_point(field_release:NetworkMessage.player_state)
  if (_internal_has_player_state()) {
    clear_has_data();
      ::PlayerStateMessage* temp = data_.player_state_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    data_.player_state_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PlayerStateMessage& NetworkMessage::_internal_player_state() const {
  return _internal_has_player_state()
      ? *data_.player_state_
      : *reinterpret_cast< ::PlayerStateMessage*>(&::_PlayerStateMessage_default_instance_);
}
inline const ::PlayerStateMessage& NetworkMessage::player_state() const {
  // @@protoc_insertion_point(field_get:NetworkMessage.player_state)
  return _internal_player_state();
}
inline ::PlayerStateMessage* NetworkMessage::unsafe_arena_release_player_state() {
  // @@protoc_insertion_point(field_unsafe_arena_release:NetworkMessage.player_state)
  if (_internal_has_player_state()) {
    clear_has_data();
    ::PlayerStateMessage* temp = data_.player_state_;
    data_.player_state_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void NetworkMessage::unsafe_arena_set_allocated_player_state(::PlayerStateMessage* player_state) {
  clear_data();
  if (player_state) {
    set_has_player_state();
    data_.player_state_ = player_state;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NetworkMessage.player_state)
}
inline ::PlayerStateMessage* NetworkMessage::_internal_mutable_player_state() {
  if (!_internal_has_player_state()) {
    clear_data();
    set_has_player_state();
    data_.player_state_ = CreateMaybeMessage< ::PlayerStateMessage >(GetArena());
  }
  return data_.player_state_;
}
inline ::PlayerStateMessage* NetworkMessage::mutable_player_state() {
  // @@protoc_insertion_point(field_mutable:NetworkMessage.player_state)
  return _internal_mutable_player_state();
}

inline bool NetworkMessage::has_data() const {
  return data_case() != DATA_NOT_SET;
}
inline void NetworkMessage::clear_has_data() {
  _oneof_case_[0] = DATA_NOT_SET;
}
inline NetworkMessage::DataCase NetworkMessage::data_case() const {
  return NetworkMessage::DataCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MessageType>() {
  return ::MessageType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_NetworkMessage_2eproto
